//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 09:56:50 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebay.com/marketplace/search/v1/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package addl.lion.training.soap.wsdl;
