//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.26 at 09:56:50 PM EET 
//


package addl.lion.training.soap.wsdl;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceTreatmentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriceTreatmentEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="STP"/&gt;
 *     &lt;enumeration value="MAP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PriceTreatmentEnum")
@XmlEnum
public enum PriceTreatmentEnum {


    /**
     * 
     * 								STP stands for Strike-Through Pricing.
     * 							
     * 
     */
    STP,

    /**
     * 
     * 								MAP stands for Minimum Advertised Price.
     * 							
     * 
     */
    MAP;

    public String value() {
        return name();
    }

    public static PriceTreatmentEnum fromValue(String v) {
        return valueOf(v);
    }

}
